### ISSUE TITLE
测试版v 1.1.1 桌面歌词以及托盘bug

### ISSUE THREAD

**Issue by zw-95** [jsososo/soso-music#10]
1. 桌面歌词拖动操作不太正常，很难点到；
 拖了多次之后，展示会缺少下半部分；
![image](https://user-images.githubusercontent.com/35022819/115010670-40aeea00-9ee0-11eb-8eb1-198ab52e35c3.png)
歌词宽度不够，导致调大字体后右边遮挡
![image](https://user-images.githubusercontent.com/35022819/115010626-35f45500-9ee0-11eb-9f94-eef986b18400.png)
2. 使用托盘不喜欢操作或使用播放界面的不喜欢操作，此时歌曲为未收藏状态，但托盘展示状态未变
![image](https://user-images.githubusercontent.com/35022819/115011008-b024d980-9ee0-11eb-8e5a-1f7fb3f53e7e.png)

**Comment by jsososo** [comment]
已了解，拖动问题目前主要是基于mac开发，mac下是正常的，关于windows的后续版本会尝试修复

**Comment by mymine** [comment]
> 已了解，拖动问题目前主要是基于mac开发，mac下是正常的，关于windows的后续版本会尝试修复

可以编译下Linux版本吗
