### ISSUE TITLE
没有关闭按钮

### ISSUE THREAD

**Issue by NutsKing** [jsososo/soso-music#2]
不知道是我没找到还是压根没有设计。我没有找到关闭软件的按钮，如果我直接在任务栏强制退出，会导致下一次打开报错！
![image](https://user-images.githubusercontent.com/24631204/110540278-e73aea80-80eb-11eb-84f3-d6b39c89ae59.png)

**Comment by jsososo** [comment]
在 release 里有新包，解决了关闭按钮，没有推正式版是因为下载流量的问题，可能会再攒一攒，然后正好最近比较忙，强退那个看起来是因为强退没有杀掉起的后台服务，导致端口被占用了，目前的退出是系统托盘里右击退出，之后我会加到明确的按钮里
