### ISSUE TITLE
希望未来能添加的功能

### ISSUE THREAD

**Issue by Jasonfranchise** [jsososo/soso-music#6]
谢谢作者能写出那么好的软件还开源。
没啥缺点但希望以后假如可以的话，作者能添加自由修改server和端口的功能。

**Comment by jsososo** [comment]
目前是有修改端口的功能的，在设置里修改就行，server的话暂时不提供，因为有些功能是需要本地存储的，如果多个客户端指向同一个服务的话可能会出问题

**Comment by Jasonfranchise** [comment]
谢谢回复，是我思虑不周
